---
title: "Tareita 2   17-09-2025"
author: "Diana Laura Pais Felipe     Matrícula:23-002-0030"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    theme: bootstrap
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Generación de números aleatorios normales

```{r}
# Datos
q1 <- 1000; q2 <- 10000; q3 <- 30000;
q4 <- 50000; q5 <- 75000; q6 <- 100000;

```

## Gráficas de normales (0,1)

### Gráficas de dispersión

```{r}
media <- 0
desvstd <- 1
n1 <- rnorm(q1,media,desvstd);
n2 <- rnorm(q2,media,desvstd); 
n3 <- rnorm(q3,media,desvstd);
n4 <- rnorm(q4,media,desvstd);
n5 <- rnorm(q5,media,desvstd); 
n6 <- rnorm(q6,media,desvstd);
```

```{r}
mititulo1 <- paste0("Num de ",q1," VA N(",media,",",desvstd,")")
mititulo2 <- paste0("Num de ",q2," VA N(",media,",",desvstd,")")
mititulo3 <- paste0("Num de ",q3," VA N(",media,",",desvstd,")")
mititulo4 <- paste0("Num de ",q4," VA N(",media,",",desvstd,")")
mititulo5 <- paste0("Num de ",q5," VA N(",media,",",desvstd,")")
mititulo6 <- paste0("Num de ",q6," VA N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")

par(mfrow = c(2, 3))
plot(n1,main=mititulo1,
     col = "lightgreen",
     xlab = "VA generadas",ylab = etiquetay)
plot(n2,main=mititulo2,
     col = "orange",
     xlab = "VA generadas",ylab = etiquetay)
plot(n3,main=mititulo3,
     col = "brown",
     xlab = "VA generadas",ylab = etiquetay)
plot(n4,main=mititulo4,
     col = "gray",
     xlab = "VA generadas",ylab = etiquetay)
plot(n5,main=mititulo5,
     col = "blue",
     xlab = "VA generadas",ylab = etiquetay)
plot(n6,main=mititulo6,
     col = "purple",
     xlab = "VA generadas",ylab = etiquetay)
```

### Histogramas

```{r}
mititulo1 <- paste0("Histograma de ",q1," VA N(",media,",",desvstd,")")
mititulo2 <- paste0("Histograma de ",q2," VA N(",media,",",desvstd,")")
mititulo3 <- paste0("Histograma de ",q3," VA N(",media,",",desvstd,")")
mititulo4 <- paste0("Histograma de ",q4," VA N(",media,",",desvstd,")")
mititulo5 <- paste0("Histograma de ",q5," VA N(",media,",",desvstd,")")
mititulo6 <- paste0("Histograma de ",q6," VA N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")

par(mfrow = c(2, 3))
hist(n1,main=mititulo1,
     col = "lightgreen",
     xlab = "VA generadas",ylab = etiquetay)
hist(n2,main=mititulo2,
     col = "orange",
     xlab = "VA generadas",ylab = etiquetay)
hist(n3,main=mititulo3,
     col = "brown",
     xlab = "VA generadas",ylab = etiquetay)
hist(n4,main=mititulo4,
     col = "gray",
     xlab = "VA generadas",ylab = etiquetay)
hist(n5,main=mititulo5,
     col = "blue",
     xlab = "VA generadas",ylab = etiquetay)
hist(n6,main=mititulo6,
     col = "purple",
     xlab = "VA generadas",ylab = etiquetay)
```

### Curva de normales (0,1)

```{r}
x <- seq(-1, 1, length = 100)
curve(dnorm(x, mean=0, sd=1), 
      from=-4, to=4, lwd=3, col="blue",
      main = "N(0, 1)", xlab = "X", ylab = "f(x)")
```

## Gráficas de normales (-1,1)

### Gráficas de dispersión

```{r}
media <- -1 
desvstd <- 1
n1 <- rnorm(q1,media,desvstd);
n2 <- rnorm(q2,media,desvstd); 
n3 <- rnorm(q3,media,desvstd);
n4 <- rnorm(q4,media,desvstd);
n5 <- rnorm(q5,media,desvstd); 
n6 <- rnorm(q6,media,desvstd);
```

```{r}
mititulo1 <- paste0("Num de ",q1," VA N(",media,",",desvstd,")")
mititulo2 <- paste0("Num de ",q2," VA N(",media,",",desvstd,")")
mititulo3 <- paste0("Num de ",q3," VA N(",media,",",desvstd,")")
mititulo4 <- paste0("Num de ",q4," VA N(",media,",",desvstd,")")
mititulo5 <- paste0("Num de ",q5," VA N(",media,",",desvstd,")")
mititulo6 <- paste0("Num de ",q6," VA N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")

par(mfrow = c(2, 3))
plot(n1,main=mititulo1,
     col = "lightgreen",
     xlab = "VA generadas",ylab = etiquetay)
plot(n2,main=mititulo2,
     col = "orange",
     xlab = "VA generadas",ylab = etiquetay)
plot(n3,main=mititulo3,
     col = "brown",
     xlab = "VA generadas",ylab = etiquetay)
plot(n4,main=mititulo4,
     col = "gray",
     xlab = "VA generadas",ylab = etiquetay)
plot(n5,main=mititulo5,
     col = "blue",
     xlab = "VA generadas",ylab = etiquetay)
plot(n6,main=mititulo6,
     col = "purple",
     xlab = "VA generadas",ylab = etiquetay)
```

### Histogramas

```{r}
mititulo1 <- paste0("Histograma de ",q1," VA N(",media,",",desvstd,")")
mititulo2 <- paste0("Histograma de ",q2," VA N(",media,",",desvstd,")")
mititulo3 <- paste0("Histograma de ",q3," VA N(",media,",",desvstd,")")
mititulo4 <- paste0("Histograma de ",q4," VA N(",media,",",desvstd,")")
mititulo5 <- paste0("Histograma de ",q5," VA N(",media,",",desvstd,")")
mititulo6 <- paste0("Histograma de ",q6," VA N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")

par(mfrow = c(2, 3))
hist(n1,main=mititulo1,
     col = "lightgreen",
     xlab = "VA generadas",ylab = etiquetay)
hist(n2,main=mititulo2,
     col = "orange",
     xlab = "VA generadas",ylab = etiquetay)
hist(n3,main=mititulo3,
     col = "brown",
     xlab = "VA generadas",ylab = etiquetay)
hist(n4,main=mititulo4,
     col = "gray",
     xlab = "VA generadas",ylab = etiquetay)
hist(n5,main=mititulo5,
     col = "blue",
     xlab = "VA generadas",ylab = etiquetay)
hist(n6,main=mititulo6,
     col = "purple",
     xlab = "VA generadas",ylab = etiquetay)
```

### Curva de normales (-1,1)

```{r}
x <- seq(-1, 1, length = 100)
curve(dnorm(x, mean=0, sd=1), 
      from=-4, to=4, lwd=3, col="blue",
      main = "N(0, 1)", xlab = "X", ylab = "f(x)")
```

## Gráficas de normales (0,2)

### Gráficas de dispersión

```{r}
media <- -0 
desvstd <- 2
n1 <- rnorm(q1,media,desvstd);
n2 <- rnorm(q2,media,desvstd); 
n3 <- rnorm(q3,media,desvstd);
n4 <- rnorm(q4,media,desvstd);
n5 <- rnorm(q5,media,desvstd); 
n6 <- rnorm(q6,media,desvstd);
```

```{r}
mititulo1 <- paste0("Num de ",q1," VA N(",media,",",desvstd,")")
mititulo2 <- paste0("Num de ",q2," VA N(",media,",",desvstd,")")
mititulo3 <- paste0("Num de ",q3," VA N(",media,",",desvstd,")")
mititulo4 <- paste0("Num de ",q4," VA N(",media,",",desvstd,")")
mititulo5 <- paste0("Num de ",q5," VA N(",media,",",desvstd,")")
mititulo6 <- paste0("Num de ",q6," VA N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")

par(mfrow = c(2, 3))
plot(n1,main=mititulo1,
     col = "lightgreen",
     xlab = "VA generadas",ylab = etiquetay)
plot(n2,main=mititulo2,
     col = "orange",
     xlab = "VA generadas",ylab = etiquetay)
plot(n3,main=mititulo3,
     col = "brown",
     xlab = "VA generadas",ylab = etiquetay)
plot(n4,main=mititulo4,
     col = "gray",
     xlab = "VA generadas",ylab = etiquetay)
plot(n5,main=mititulo5,
     col = "blue",
     xlab = "VA generadas",ylab = etiquetay)
plot(n6,main=mititulo6,
     col = "purple",
     xlab = "VA generadas",ylab = etiquetay)
```

### Histogramas

```{r}
mititulo1 <- paste0("Histograma de ",q1," VA N(",media,",",desvstd,")")
mititulo2 <- paste0("Histograma de ",q2," VA N(",media,",",desvstd,")")
mititulo3 <- paste0("Histograma de ",q3," VA N(",media,",",desvstd,")")
mititulo4 <- paste0("Histograma de ",q4," VA N(",media,",",desvstd,")")
mititulo5 <- paste0("Histograma de ",q5," VA N(",media,",",desvstd,")")
mititulo6 <- paste0("Histograma de ",q6," VA N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")

par(mfrow = c(2, 3))
hist(n1,main=mititulo1,
     col = "lightgreen",
     xlab = "VA generadas",ylab = etiquetay)
hist(n2,main=mititulo2,
     col = "orange",
     xlab = "VA generadas",ylab = etiquetay)
hist(n3,main=mititulo3,
     col = "brown",
     xlab = "VA generadas",ylab = etiquetay)
hist(n4,main=mititulo4,
     col = "gray",
     xlab = "VA generadas",ylab = etiquetay)
hist(n5,main=mititulo5,
     col = "blue",
     xlab = "VA generadas",ylab = etiquetay)
hist(n6,main=mititulo6,
     col = "purple",
     xlab = "VA generadas",ylab = etiquetay)
```

### Curva de normales (0,2)

```{r}
x <- seq(-1, 1, length = 100)
curve(dnorm(x, mean=0, sd=1), 
      from=-4, to=4, lwd=3, col="blue",
      main = "N(0, 1)", xlab = "X", ylab = "f(x)")
```

## Gráficas de normales (0,2.5)

### Gráficas de dispersión

```{r}
media <- 0 
desvstd <- 2.5
n1 <- rnorm(q1,media,desvstd);
n2 <- rnorm(q2,media,desvstd); 
n3 <- rnorm(q3,media,desvstd);
n4 <- rnorm(q4,media,desvstd);
n5 <- rnorm(q5,media,desvstd); 
n6 <- rnorm(q6,media,desvstd);
```

```{r}
mititulo1 <- paste0("Num de ",q1," VA N(",media,",",desvstd,")")
mititulo2 <- paste0("Num de ",q2," VA N(",media,",",desvstd,")")
mititulo3 <- paste0("Num de ",q3," VA N(",media,",",desvstd,")")
mititulo4 <- paste0("Num de ",q4," VA N(",media,",",desvstd,")")
mititulo5 <- paste0("Num de ",q5," VA N(",media,",",desvstd,")")
mititulo6 <- paste0("Num de ",q6," VA N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")

par(mfrow = c(2, 3))
plot(n1,main=mititulo1,
     col = "lightgreen",
     xlab = "VA generadas",ylab = etiquetay)
plot(n2,main=mititulo2,
     col = "orange",
     xlab = "VA generadas",ylab = etiquetay)
plot(n3,main=mititulo3,
     col = "brown",
     xlab = "VA generadas",ylab = etiquetay)
plot(n4,main=mititulo4,
     col = "gray",
     xlab = "VA generadas",ylab = etiquetay)
plot(n5,main=mititulo5,
     col = "blue",
     xlab = "VA generadas",ylab = etiquetay)
plot(n6,main=mititulo6,
     col = "purple",
     xlab = "VA generadas",ylab = etiquetay)
```

### Histogramas

```{r}
mititulo1 <- paste0("Histograma de ",q1," VA N(",media,",",desvstd,")")
mititulo2 <- paste0("Histograma de ",q2," VA N(",media,",",desvstd,")")
mititulo3 <- paste0("Histograma de ",q3," VA N(",media,",",desvstd,")")
mititulo4 <- paste0("Histograma de ",q4," VA N(",media,",",desvstd,")")
mititulo5 <- paste0("Histograma de ",q5," VA N(",media,",",desvstd,")")
mititulo6 <- paste0("Histograma de ",q6," VA N(",media,",",desvstd,")")
etiquetay <- paste0("N(",media,",",desvstd,")")

par(mfrow = c(2, 3))
hist(n1,main=mititulo1,
     col = "lightgreen",
     xlab = "VA generadas",ylab = etiquetay)
hist(n2,main=mititulo2,
     col = "orange",
     xlab = "VA generadas",ylab = etiquetay)
hist(n3,main=mititulo3,
     col = "brown",
     xlab = "VA generadas",ylab = etiquetay)
hist(n4,main=mititulo4,
     col = "gray",
     xlab = "VA generadas",ylab = etiquetay)
hist(n5,main=mititulo5,
     col = "blue",
     xlab = "VA generadas",ylab = etiquetay)
hist(n6,main=mititulo6,
     col = "purple",
     xlab = "VA generadas",ylab = etiquetay)
```

### Curva de normales (0,2.5)

```{r}
x <- seq(-1, 1, length = 100)
curve(dnorm(x, mean=0, sd=1), 
      from=-4, to=4, lwd=3, col="blue",
      main = "N(0, 1)", xlab = "X", ylab = "f(x)")
```
